### ISSUE TITLE
syntax highlighting of ocaml values in the generated HTML pages

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml-doc/odoc#100]
Hello,

Sorry, I am not sure if it is related to odig or odoc.
As a user, I would read more easily the generated documentation if ocaml values
were syntax highlighted; for example using the same color scheme than what
emacs' tuareg-mode is using.
Maybe this feature should be ON by default, but there should be an option do disable it.

Regards,
F.

**Comment by dbuenzli** [comment]
Already tracked in #66.
