### ISSUE TITLE
Don't needlessly wrap everything in `div`'s 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#17]
It makes stylesheets a nightmare to develop.

For example here http://docs.mirage.io/odoc/ocaml/Scanf/index.html you have: 

```
<div class="doc"><h6>...</h6></div>
<div class="doc"><h6>...</h6></div>
```

Not only does this [`div`itis](https://en.wiktionary.org/wiki/divitis) prevents me of writing simple css rules like (`h6 + h6`) the added tags are purely worthless.

Basically a mli rendered to html should be seen as a literate document where you a proper document interleaved with properly delineated formal definitions.

Also this `div` wrapping seems random. For example it doesn't appear here: 

http://docs.mirage.io/odoc/react/React/index.html#basics

(where we do see however horrible `br` and lack of `p` (#10))

**Comment by trefis** [comment]
The `div` wrapping is not random, at least not the `<div class="doc">` which we put around each "docstring".
Sometimes the docstring will containt only `{6 Some title}` explaining the `<div class="doc"><h6>Some title</h6></div>` as is the case on your first link, `scanf.mli` starts like this:
```ocaml
(** {6 Introduction} *)

(** {7 Functional input with format strings} *)

(** ... *)
```

While on the second example you have one big docstring which happen to contain some title in the middle ( https://github.com/dbuenzli/react/blob/master/src/react.mli#L821 ), explaining why there is no `div` around the `h1` tag there.

I can nevertheless simply remove the `div` wrapping around toplevel docstrings (i.e. ones which are not attached to a particular node); I assume we want to keep the 
```
<div class = "spec $(KIND)">
  <a href="#$(KIND)-$(ID)" class="anchor"></a>
  <div class="def $(KIND)"><code>...</code></div>
  <div class="doc">...</div>
</div>
```
structure you suggested in #23 , i.e. keep the wrapping inside "spec" divs.

Does that seem like what you'd want?

**Comment by dbuenzli** [comment]
Yes.
