### ISSUE TITLE
Better semantics 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#18]
1. If we keep the embedding ability (see #9) then the wrapping `<div class='odoc-doc'>` should be replaced by an `<article class='odoc'>` ([semantics](https://www.w3.org/TR/html5/sections.html#the-article-element)). 
2. The introductory `<div class=intro>` should by simply be replaced by a classless `<header>` tag which can be used for [introductory contents](https://www.w3.org/TR/html5/sections.html#the-header-element).
3. After the `header` tag there should be no enclosing `div` for the literate text and definitions, simply add them sequentially after the `header` tag.

**Comment by dbuenzli** [comment]
So basically with the other issues (#17, #10, #9). The toplevel structure we'd get is: 

```
<article class='odoc'>
<nav><!-- Up link and others --></nav>
<header><!-- Module preamble --></header>
... <!-- Sequence of marked up text interleaved with definitions -->
</article>
```
Note that if embedding is not important (I personally don't care), we could drop the `article` and simply use the html `body`. If it is then an an option should be added so that odoc only outputs the `article` otherwise it's just useless and puts noise is the stylesheet for nothing (everything needs to be prefixed by the `.odoc-doc` class).

**Comment by dbuenzli** [comment]
Also if we want to convey correct structure to screen readers I think we should `<h1>` for the module `name` and then start mapping `"{1"` to `<h2>` on.  We could have achieved using `<h1>` for `"{1"` by wrapping what comes after the `<header>` in an `<article>` tag but it seems that the html5 outline algorithm doesn't exist [in practice](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines). 

See also the discussion in [MPR7364](http://caml.inria.fr/mantis/view.php?id=7363).

**Comment by trefis** [comment]
I replaced the `<div class="intro">` by the `<header>` tag, I added the `<nav>` tag and I map `{n ...}` to `<h(n+1)>...</h(n+1)>` as suggested (switching to `<div class="h(n+1)">` when `n + 1 > 6`).

As I had removed the `<div class="odoc-doc">` previously I am not sure whether we still want the `<article>` tag or not, and if yes whether it should replace `<body>` or be its only child.

Apart from that last bit, I think we're set.

**Comment by dbuenzli** [comment]
Broadly the structure of the markup is good. I'll close this and reopen more specific issues if needed.
