### ISSUE TITLE
Specify file to output in `odoc compile`

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#2]
The fact that `odoc compile` doesn't allow to choose the name of the output file is a bit strange. If I'm not mistaken `odoc compile` can only output a single file, so the fact that `-o` specifies an output directory is a little bit odd. Here's what I would expect from a cli point of view:

```
odoc compile bla.cmti                  # Generates bla.odoc in the cwd
odoc compile -o path/to/file bla.cmti  # Generates the output in path/to/file
odoc compile -o - bla.cmti             # Generates output on stdout. 
```

**Comment by lpw25** [comment]
I can't decide what the right approach is here.

The `link` command generates a directory and assumes a particular directory structure around it in order the generate the links. So it seems natural that you would use a directory for its output.

However, `link` does not make such assumptions about the structure of directories containing `odoc` files, and neither does `compile` make such assumptions about where it is outputing its files. So the user could use whatever directory structure they like for storing `.odoc` files. This implies that directly specifying the output file would be more natural.

So it seems like a trade off between `compile` behaving like `link` for consistency or behaving in the way most natural for it.

**Comment by dbuenzli** [comment]
> compile behaving like link for consistency

I think if you wanted to be consistant then for `link`, `-o` should specify the name of the output directory and another option `-d` should specify the directory in which you want that directory to be written.

**Comment by lpw25** [comment]
True. I think we should probably just go with your original suggestion. It's probably fine for `link` and `compile` to disagree about how they interpret `-o`.
