### ISSUE TITLE
odoc is confused by subscripts ending with `v`.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#20]
```
opam install gg && opkg odoc gg
opkg: [WARNING] gg: /Users/dbuenzli/.opam/4.03.0/lib/gg/gg.cmti: No cmti found for Unix (331e41ad213579d006efd84f19005bd5)
opkg: [WARNING] gg: /Users/dbuenzli/.opam/4.03.0/lib/gg/gg.cmti: No cmti found for Bigarray (7cb259b8efbf4550648d25651a3342ee)
Error src/gg.mli, line 3225, col 28 to line 3225, col 30: unmatched 'v}'
Error src/gg.mli, line 3228, col 45 to line 3228, col 47: unmatched 'v}'
Error src/gg.mli, line 3238, col 35 to line 3238, col 37: unmatched 'v}'
Error src/gg.mli, line 3241, col 55 to line 3241, col 57: unmatched 'v}'
```

The corresponding lines are here:

https://github.com/dbuenzli/gg/blob/master/src/gg.mli#L3225
https://github.com/dbuenzli/gg/blob/master/src/gg.mli#L3228
https://github.com/dbuenzli/gg/blob/master/src/gg.mli#L3238
https://github.com/dbuenzli/gg/blob/master/src/gg.mli#L3241

**Comment by trefis** [comment]
@lpw25 octavius problem.

**Comment by lpw25** [comment]
Fixed by https://github.com/ocaml-doc/octavius/commit/36cbb6ff478787f04812f4ac65bc86d446b85132

**Comment by dbuenzli** [comment]
Still get the same error with octavius 52270d64

```
> odig odoc gg --force 
odig: [WARNING] gg: /Users/dbuenzli/.opam/4.03.0/lib/gg/gg.cmti: No cmti found for Unix (331e41ad213579d006efd84f19005bd5)
odig: [WARNING] gg: /Users/dbuenzli/.opam/4.03.0/lib/gg/gg.cmti: No cmti found for Bigarray (7cb259b8efbf4550648d25651a3342ee)
Error src/gg.mli, line 3225, col 28 to line 3225, col 30: unmatched 'v}'
Error src/gg.mli, line 3228, col 45 to line 3228, col 47: unmatched 'v}'
Error src/gg.mli, line 3238, col 35 to line 3238, col 37: unmatched 'v}'
Error src/gg.mli, line 3241, col 55 to line 3241, col 57: unmatched 'v}'
```

**Comment by lpw25** [comment]
Are you sure that's with the right version. That commit removes that error message from the code base, so I can't see how it would still appear.

**Comment by trefis** [comment]
I can confirm that the problem has disappeared for me.

**Comment by dbuenzli** [comment]
Indeed after an `odig cache clear gg` that made it. Apparently there's rather a bug with `odig odoc --force`, it doesn't redo the `.odoc` files, only the `html` step.
