### ISSUE TITLE
odoc doesn't respect stop comments

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#21]
For example in uuidm we have this stop comment:

https://github.com/dbuenzli/uuidm/blob/master/src/uuidm.mli#L38-L41

`create` still shows up in `odoc`'s API doc with dubious C multiline start comments.

```
opam install uuidm && opkg ocamldoc uuidm && opkg odoc uuidm && opkg doc -c uuidm
```

**Comment by trefis** [comment]
The problem in this case is that doc-ock expects stop comments to be floating comments whereas in your example the compiler has attached the comments to `create`.

I feel like we should keep the implementation of odoc as is and you should add some blank lines in your code so they are not attached to the node.

**Comment by dbuenzli** [comment]
I think this is going to be a problem in practice. The [specification](http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#sec338) really says that everything between two `(**/**)` is dropped. It feels a little brittle to ask people to add whitespace for this to work.

**Comment by trefis** [comment]
> It feels brittle

Really? Properly handling these comments when they are attached to a node involves making some relatively ugly `Location`-based decisions.
Just asking people to add a newline here and there doesn't feel "brittle" to me and we already asked them to add such newlines in the past, e.g. to disambiguate things like:
```ocaml
val foo : 'a -> 'b
(** where do I attach? *)
val bar : 'a -> 'b
```
so it doesn't seem too crazy to make the same request in this case.

@lpw25 any opinion?

**Comment by dbuenzli** [comment]
> Really?

Yes. Your example is quite different. As you can read in the specification I linked to there's no ambiguity in a `(**/**)` comment. 

My take on this is that the comment lifting is wrongly done upstream. `(**/**)` should never get attached to a value specification.

**Comment by trefis** [comment]
I agree on both points. It's just that I don't feel like the compiler is going to be "fixed" on that point (but @lpw25 might contradict me on this?) and I'm not really keen on introducing shitty "detachment" decisions based on locations in doc-ock.

That being said I don't mind submitting a PR on the compiler just to see how it goes.

**Comment by dbuenzli** [comment]
> I'm not really keen on introducing shitty "detachment" decisions based on locations in doc-ock.

Sure it doesn't seem to be the right place to do this.

**Comment by dbuenzli** [comment]
Excellent @trefis and thanks to @damiendoligez for merging this into 4.04
