### ISSUE TITLE
Exceptions problem + general structure of definitions + link structure

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#23]
Exceptions are not well marked up. See for example http://docs.mirage.io/odoc/alcotest/Alcotest/index.html
1. They are not in a `<div class="region">` block but in a `<div class="exn">`.
2. They use invalid ocaml syntax to render, the keyword for exceptions is `exception` not `exn`.
3. They lack an anchor for referencing.

Related to the general structure #18 and #19 I would prefer if we drop the `region` class. I think each definition should be marked up as follows:

```
<div class = "spec $(KIND)">
  <a href="#$(KIND)-$(ID)" class="anchor"></a>
  <div class="def $(KIND)"><code>...</code></div>
  <div class="doc">...</div>
</div>
```

Where `$(KIND)` is the kind of construct. `spec` comes from the [vocabulary](http://caml.inria.fr/pub/docs/manual-ocaml/modtypes.html#specification) of the module system.

Regarding anchor fragments I find `#/$(ID).$(kind)` to be noisy in practice. In the above proposal I dropped the `/` and also reversed the `$(KIND)` and `$(ID)` as it then matches the order we write them in OCaml. Replaced the `.` by `-` to avoid confusion with OCaml paths.

**Comment by dbuenzli** [comment]
(Also I think it would be easier to hack urls if `type` was not abbreviated to `typ`)

**Comment by trefis** [comment]
The exception was indeed completely wrong and has been fixed.
I also updated the layout following your remarks and removed the use of the `region` class everywhere.

**Comment by dbuenzli** [comment]
This looks ok except I suggest suggest that for `$(KIND)` we actually use the OCaml keywords (`module-type` not `modt`, `type` not `typ`, etc.), replacing spaces by dashes if needed and that we replace `id.$(KIND)` by `$(KIND)-id` which makes it more the way you would write this in OCaml.

**Comment by dbuenzli** [comment]
I also notice that the strings `typ` `val` `modt` etc. are scattered as string literals in the code base. This should be defined at a single point.
