### ISSUE TITLE
References in doc strings 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#25]
are not hyperlinked and references to identifiers not wrapped in a `code` tag. 

Contrast the links in the preamble of this module: 

http://docs.mirage.io/odoc/astring/Astring/index.html
http://docs.mirage.io/astring/Astring.html

Contrast the doc string of the two first values in the `String` section here:

http://docs.mirage.io/odoc/astring/Astring/index.html
http://docs.mirage.io/astring/Astring.html

**Comment by trefis** [comment]
The first part of the issue is that odoc doesn't handle "forward references" correctly, this is blocked on @lpw25 rewrite of parts of doc-ock.

The second part (the doc string being incorrect) I will fix today.

**Comment by trefis** [comment]
I misread the odoc file, the reference is resolved and the problem is indeed in doc-ock-html, I will fix this.
