### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#26]
I think this is for octavius aswell: 

```
> opkg odoc react
Error src/react.mli, line 207, col 26 to line 207, col 27: '}' expected
```

The line is [here](https://github.com/dbuenzli/react/blob/d595442ef1b5c1fa2d8484c645ac3842ef84b572/src/react.mli#L207) and I guess it wants to complain about the `.` that is outside the list element.

**Comment by lpw25** [comment]
What would you prefer the message to be? Would `'}' or list item expected` be better?

**Comment by dbuenzli** [comment]
> '}' or list item expected be better?

Yes.

**Comment by lpw25** [comment]
Fixed by https://github.com/ocaml-doc/octavius/commit/8f90e4f5a1d4e0f9cc11a4291f8acef1bea21067.

It now gives `'{ul' not closed, expected list item or '}'`.
