### ISSUE TITLE
Odoc explodes on some `.odoc` files due to doc-ock-html

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#32]
See https://github.com/ocaml-doc/doc-ock-html/issues/5 for details and discussion.

**Comment by dbuenzli** [comment]
Well you need to `Xmlm.input` the `Dtd` signal before calling `Xmlm.input_tree` [here](https://github.com/ocaml-doc/doc-ock-html/blob/2bb8cf3ddd1125dc6e5fb1eb104c2cdfb0b47768/src/docOckHtmlDocumentation.ml#L16). The comment about using an XML parser to parse HTML remains.

**Comment by trefis** [comment]
> Either you need to get a proper html parser in the loop (which I wouldn't advise) or you should simply inject the raw html string as is and rely on people providing correct html markup (a reasonable assumption).

I'd be fine with just injecting the string, but I'm not sure tyxml will let me do that.
Ping @Drup.

**Comment by Drup** [comment]
If you are using `Tyxml.Html`, assuming you suppose the provided piece of html is a div: 
```ocaml
(Html.Unsafe.data s : Html_types.div Html.elt)
``` 
Tyxml will treat it as a big block of already encoded stuff and will not touch it.

That doesn't with jsoo's Tyxml_js, You need some innerHtml trickery (or markup).

**Comment by trefis** [comment]
Thanks @Drup !
