### ISSUE TITLE
Lost doc string

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#43]
Quite surprisingly, as far as I know this is not an attachement problem: 

http://docs.mirage.io/react/React/E/index.html#val-select
http://erratique.ch/software/react/doc/React.E.html#VALselect

The source is here 

https://github.com/dbuenzli/react/blob/1a4a86e4fa8d67bd59c77cc3180a1718fdb84b18/src/react.mli#L201-L208

**Comment by trefis** [comment]
```
$ odig odoc react
Error src/react.mli, line 207, col 26 to line 207, col 27: '{ul' not closed, expected list item or '}'
```

You have a dot outside the list item on that line at the indicated column.

**Comment by dbuenzli** [comment]
Ah yes sorry once again something that I already fixed... (which is why I couldn't see it in the dev-repo sources)
