### ISSUE TITLE
Paragraphs are not recognized in list elements

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#44]
See the first bullet in the docstring of this element 

http://docs.mirage.io/react/React/S/index.html#val-fix
http://erratique.ch/software/react/doc/React.S.html#VALfix

Source:

https://github.com/dbuenzli/react/blob/1a4a86e4fa8d67bd59c77cc3180a1718fdb84b18/src/react.mli#L485-L497

**Comment by trefis** [comment]
So, I fixed the particular problem you pointed out.
But as a side effect, list elements always contain paragraphs and I suspect that might not be "the right thing"?

**Comment by dbuenzli** [comment]
If there's a single paragraph it would better not.
