### ISSUE TITLE
Display of unresolved references

### ISSUE THREAD

**Issue by trefis** [ocaml-doc/odoc#47]
In #33 @dbuenzli noticed that sometimes the "text" part of a link is lost when the reference is unresolved, compare for example :
- http://erratique.ch/software/fpath/doc/Fpath (ocamldoc)
- http://docs.mirage.io/fpath/Fpath/index.html (odoc)

where "important tips" is lost and truncated to "tips".

This is a "known problem", see this [FIXME](https://github.com/ocaml-doc/doc-ock-html/blob/master/src/docOckHtmlDocumentation.ml#L138).

The problem is that we're trying a "best effort" approach where if the path we are pointing to is not resolved but some prefix of it is, we will still make the prefix clickable. In such cases however, we display the path and drop the user supplied text.

We could do a bit better than what we are doing now, i.e. only do that when we **know** that some part of the path is resolved, otherwise if none of it is, just display the user text. But it's not great.

Maybe we should just not try to link if a path is not completely resolved?

Regardless, do we want some kind of markup to indicate that "*oh, we failed to resolve that reference*"?

**Comment by lpw25** [comment]
I think we should only do the "best effort" thing for references without text. References with text only care about the full path (since they are deliberately hiding the rest of the path) so a best effort doesn't help them. References without text intend to display the whole path, so a best effort is better than a dead link for them.

**Comment by dbuenzli** [comment]
There are hints in https://github.com/ocaml-doc/odoc/issues/42 on how unresolved references should be rendered.
