### ISSUE TITLE
octavius unicode support

### ISSUE THREAD

**Issue by trefis** [ocaml-doc/odoc#48]
Title was: *odoc drops a good part of fpath:fpath.mli*

Compare [ocamldoc](http://erratique.ch/software/fpath/doc/Fpath#tips) with [odoc](http://docs.mirage.io/fpath/Fpath/index.html#module-Map) (just before the tips section).

Reported in #33 .

**Comment by trefis** [comment]
```$ odig odoc fpath
odig: [WARNING] fpath: /home/trefis/.opam/4.03.0/lib/fpath/fpath.cmti: No cmti found for Result (fdad00749536fad60f1dc5845deb7c7c)
Error src/fpath.mli, line 655, col 37 to line 655, col 42: '{ul' not closed, expected list item or '}'
```

And indeed, [on line 655](https://github.com/dbuenzli/fpath/blob/v0.7.1/src/fpath.mli#L655).
Which as since been fixed by this [commit](https://github.com/dbuenzli/fpath/commit/ac84f7ce8792e92a3ad05376ca7de5ea2d0f95a5).

Pinning the git repo of fpath does indeed fix the problem, the examples are included and the link to "important tips" in the preamble is now resolved and so displays the expected text.

**Comment by trefis** [comment]
Octavius should probably be more resilient to weird utf-whatever symbols however, reopening.

**Comment by dbuenzli** [comment]
> Octavius should probably be more resilient to weird utf-whatever symbols however, reopening.

Simply *reporting* errors should be fine.

**Comment by dbuenzli** [comment]
Ah but it does report the error, I think it's fine that way.

**Comment by trefis** [comment]
Ah indeed, the character is outside the list item.
So it's fine.
