### ISSUE TITLE
Markup for variants and polyvars

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#51]
Examples:

http://docs.mirage.io/doc-ock/Ocamlary/index.html#type-variant
http://docs.mirage.io/doc-ock/Ocamlary/index.html#type-poly_variant

The markup should follow what was proposed for record (#50), which means: 

1. The table tag should be classified with `variant` (I don't think we should distinguish polyvars what do you think ?)
2. Remove `cons` class from `tr`. 
3. Each row should have only two `td` columns per row and no inner `div`. The first `td` should have the as attribute the the `id` that the current inner `div` has, be classified with `def constructor` and simply contain the anchor and the constructor definition as you would render a function type. The second `td` should have the comment and the class `doc`.
4. This should be done for polymorphic variant type definitions (but now for the polyvars that occur in function signatures).

**Comment by trefis** [comment]
I wonder if we should not perhaps put the `|` in a separate column. That way when the text in the constructor cell is wrapped on a new line, it appears "indented", i.e. it starts again under the constructor, not under the pipe.
What do you think?

PS: at the moment only "normal" variants have been updated, polymorphic variants are a bit more work and will be done "later".

**Comment by trefis** [comment]
This is done, but the output doesn't look so great, the CSS will need updating.
There are examples in ocamlary if you want to have a look.

**Comment by dbuenzli** [comment]
> This is done, but the output doesn't look so great, the CSS will need updating.

It doesn't seem too bad, do you have a particular example in mind. Though we have the same problem as for records with the closing paren though, I haven't had a close look at how we could solve this yet.  One thing that looks quite bad is inline records, I guess we need a table in the td for the record like you would do for a record type def.
