### ISSUE TITLE
Includes lookup and capitalized `.odoc` files

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#53]
Using the recent `{!modules: }` support on the batteries package, the link to BatteriesConcreteQueue was not being done. 

It seems that this is due to the `.odoc` file having a capitalized file name (the filename is derived from the `cmi`, see https://github.com/ocaml-batteries-team/batteries-included/issues/701). 

Should `odig` uncapitalize them ? Or is this a problem we'd like to solve ?

**Comment by trefis** [comment]
I think this should be fixed inside odoc.

(I fail to see the relation with #9 however)

**Comment by dbuenzli** [comment]
> (I fail to see the relation with #9 however)

Number mismatch...

**Comment by dbuenzli** [comment]
Nb I think ocamldoc suffers from the same problem (at least odig's ocamldocs for batteries also have the same problem).

**Comment by trefis** [comment]
Fixed by https://github.com/ocaml-doc/odoc/commit/259122a2f8a6c44de75631dd004b351576ded764.
