### ISSUE TITLE
Manuals written in odoc

### ISSUE THREAD

**Issue by Drup** [ocaml-doc/odoc#61]
@trefis mentioned the new `.mld` syntax that allows to create a "home page" for a package, similarly to `-index` for ocamldoc.

I would really like the ability to "link" together multiple .mld documents, with one generated web page per file and the ability to make links. This would effectively allow to write complete multi-page manuals in odoc.

**Comment by dbuenzli** [comment]
I would also be interested in being able to process `.mld` files to html fragments e.g. to solve https://github.com/dbuenzli/odig/issues/18

**Comment by trefis** [comment]
Proper support for `.mld` files might not be too hard to add.

With the design I have in mind, you could call `odoc compile` on `foo.mld`, which would generate a `foo.odoc`, calling `odoc html` on it would then produce `foo.html`. 
(with this scheme the `-index-for` option would disappear, one would just have a `index.mld` file)

The annoying point here is that not only do the `.mld` files need to have unique names, they also need to have distinct names from all the units in the package.
Of course, one could always use the `-o` option to avoid that restriction, but if people want things to automagically work with odig, jbuilder, etc. then I believe the restriction applies.

Does that sound reasonable to you?

**Comment by dbuenzli** [comment]
> The annoying point here is that not only do the .mld files need to have unique names, they also need to have distinct names from all the units in the package.

I'm not sure I fully grasp the implications of this. But is seems that each `f.mld` becomes as if module `F` was defined at the toplevel of the module hierarchy, that doesn't seem a reasonable solution to me. I guess you are proposing this because it allows to reuse the whole link resolution procedures without any other changes ? 

In any case I would like to be able to output `html` *fragments*, i.e. only the content of what would be in the `body` tag of the page. So a `--fragment` cli should be added to `odoc html`.

**Comment by Drup** [comment]
I think that's an acceptable constraint, especially if we have pack-like functionalitie to namespace these files properly.

**Comment by trefis** [comment]
> But is seems that each f.mld becomes as if module F was defined at the toplevel of the module hierarchy, that doesn't seem a reasonable solution to me. I guess you are proposing this because it allows to reuse the whole link resolution procedures without any other changes ? 

Yes and yes.

> In any case I would like to be able to output html fragments, i.e. only the content of what would be in the body tag of the page. So a --fragment cli should be added to odoc html.

That's an other issue :)

> I think that's an acceptable constraint, especially if we have pack-like functionalitie to namespace these files properly.

Not sure what you mean by pack-like functionalities, but I'd guess we don't have them.

**Comment by dbuenzli** [comment]
> Yes and yes.

I think there are two use cases for `.mld` processing. 

1. Processing doc fragments that make reference to API docs. This is for example what I need in https://github.com/dbuenzli/odig/issues/19
2. Processing full doc files that make references to API docs but whose sections we also might want to refer from the API docs.

For 1. I think your proposal is impractical.

But for 2. I see that your proposal solves the bidirection xrefs easily. I'm also quite fond of the idea of defining a package's documentation via `cmti` files + `mld` files that are the manual and that by simpling installing these `odig` can do its job at providing a good view of your switches with manuals even cross-linking across packages. 

However I still find the limitations about names a bit annoying. Couldn't we reserve a toplevel identifier (and if possible not an ocaml module identifier) `id` so that we can xref a `file.mld` from the manual using {!id.file} and generate the manual in say `_id` so that it doesn't clash with module names ?

**Comment by Drup** [comment]
@dbuenzli The use case I'm interested in (and the subject of this feature request) is clearly 2. And yes, I find the fact that we could simply install them, and odig can work it's magic.

What I meant by pack-like, and I believe it's equivalent to @dbuenzli's proposition, would be to specify a top level module name for a group of `mld` files. For example, the lwt manual about C bindings would be `bindings.mld` and under the module name `LwtMan.Bindings`, and everyone can crosslink arbitrarily while avoiding conflicts. Using a syntactic marker that is not valid in OCaml module names is fine too.

**Comment by dbuenzli** [comment]
FWIW I found that `ocamldoc` (the tool) doesn't choke on `{!^Bla}` references but simply reports them as not found elements. 

So I'm naively proposing to generate the `.mld` in `_doc` directory of the package and have `odoc` redirect the `{!^Pkg.Bla}` references to `pkg/_doc/Bla.html` (alternatively we could have `mld`s generated in `pkg/` and the modules in a `pkg/api` subdir).

But maybe someone like @lpw25 who has intimate knowledge of the ocamldoc language can make a better proposal while being aware of the pitfalls.

**Comment by trefis** [comment]
So, we've discussed this a bit with @lpw25 and here's our current plan:

## produced files and urls

`foo.mld` will be transformed into `page-Foo.odoc` and later `page-Foo/index.html` by odoc.

This allows us to keep a flat directory and also the urls are going to be more regular with the rest of the system (we already have `pkg/M1/M2/module-type-S/...` here we'd have `pkg/page-Foo/...`).

## references

### Digression

This is a somewhat independent issue but: ocamldoc's syntax for references is vaguely broken as it doesn't (as far as we can see) allow to disambiguate the reference on the last line in the following:
```ocaml
module M : sig
  module type S : sig
    type t
  end

  module S : sig
    type t
  end
end

(** Some reference to {!M.S.t} *)
```

Indeed the syntax ocamldoc provides only allows to disambiguate the last part of the reference, but not intermediate ones. So here one cannot say: "*I want `S` to be a module type*".

We're proposing to extend the syntax for references to be able to disambiguate intermediate parts of the path.
In the previous example the fully disambiguated reference could look like this: `{!module-M.module-type-S.type-t}`.

N.B. An alternative syntax could be `{!M[module].S[module-type].t[type]}` but we have a preference for the first one (as it's closer to the urls generated by doc-ock-html). Or something better. Any ideas?

### references to pages

Assuming we do the change and go with the syntax `{!namespace-Name.namespace-Name...}`, then we'd introduce a new "namespace" called `page` for pages.
Then unambiguous references could be `{!Foo}`, `{!Foo.label}` and ambiguous ones could be expanded to `{!page-Foo}` and `{!page-Foo.label}`.

**Comment by dbuenzli** [comment]
The general plan seems good to me. However regarding syntax why not keep the [existing](https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#sss%3Acrossref) `tag:id` syntax and simply allow it to apply on each identifier of a path ?

**Comment by trefis** [comment]
Then you'd change the meaning of `{!type:M.t}`, wouldn't you?
With our plan the old syntax is still available (although "deprecated") and its semantic is unchanged.

**Comment by dbuenzli** [comment]
> Then you'd change the meaning of {!type:M.t}, wouldn't you?

Silly me.

**Comment by Drup** [comment]
@trefis The plan looks very good to me. I guess there is a reasoning behind using `page-Foo/index.html` instead of `page-Foo.html`, but you didn't detail it. Is it just being consistent with general behavior of odoc ?

Does this approach allows the pack-like functionality I described above ?

**Comment by trefis** [comment]
> I guess there is a reasoning behind using page-Foo/index.html instead of page-Foo.html, but you didn't detail it. Is it just being consistent with general behavior of odoc ?

It is. :)

> Does this approach also allows the pack/namespace-like functionality I described above

Not quite actually. Disambiguation can/will be done with a syntactic marker as mentioned previously (`{!page-Foo}`), but that only works if there is only one page `Foo` available in the "build environment" if several packages define a page with that name, then we're in trouble.
We probably just want to add another marker to disambiguate between packages I'm guessing. @lpw25 any opinion?

Btw, I just implemented the first part of the changes described above, i.e. the disambiguation. I'll start working on actually supporting pages in the coming days.
If all goes well, one should be able to write a manual using odoc before the end of the month.

**Comment by lpw25** [comment]
> any opinion?

I've always assumed we would add some form of package syntax (e.g. `{!bar::module-Foo}`) when we got around to making cross-package references work properly.

**Comment by trefis** [comment]
> > I guess there is a reasoning behind using `page-Foo/index.html` instead of `page-Foo.html`, but you didn't detail it. Is it just being consistent with general behavior of odoc ?
> 
> It is. :)

Actually, I changed my mind a bit on that: I'll now just generate `Foo.html`.
To sum up : 

.                    | foo.mld             | foo.cmti
-----------------|--------------------|----------
after compile | page-foo.odoc | foo.odoc
after html       | foo.html           | Foo/{index.html,Bar/...,...}

The reason being:
- there are no conflicts
- we can get rid of the ad-hoc `--index-for`: just call `odoc compile ... index.mld` followed by `odoc html ... page-index.odoc` and you're done.

It does make things less regular in doc-ock-html regarding the emitting of links between things, but I think it's worth it (also, doc-ock-html is just a complete mess regarding urls, and that will have to be improved soon anyway).

I currently have a dirty version that seem to work on the minimal tests I've written.
I'll clean it all up and push it on Monday and it should be fairly straightforward to update odig and jbuilder to use it.

**Comment by dbuenzli** [comment]
Excellent @trefis ! Regarding `.mld` processing and `odoc html` I really need:

> In any case I would like to be able to output html fragments, i.e. only the content of what would be in the body tag of the page. So a --fragment cli should be added to odoc html.

for https://github.com/dbuenzli/odig/issues/19 and https://github.com/dbuenzli/odig/issues/18. This would also be useful for people who wants to add "chrome" around the pages (e.g. docs.ocaml.org).

**Comment by dbuenzli** [comment]
> (also, doc-ock-html is just a complete mess regarding urls, and that will have to be improved soon anyway).

Oh when you do so please consider https://github.com/ocaml-doc/odoc/issues/27 so that package developers can check their xrefs in context.

**Comment by trefis** [comment]
Yep, these things are definitely on the todo-list, however I believe @aantron will be the one to tackle them.

Btw, one thing that I didn't "document" in my previous message is the behavior of `odoc compile -o` when the input is a .mld file (for the html step, `-o` behaves as usual):
- the argument following `-o` is restricted to be of the form `some/path/page-foo.odoc` whereas when processing `.cm{i,t,ti}` files any `some/path/foo.odoc` will be accepted.

**Comment by dbuenzli** [comment]
So I opened #89 for the fragment. 

> Btw, one thing that I didn't "document"

Please document these things were they belong to, that is in `odoc html --help`.

**Comment by trefis** [comment]
Yep, will do.
I'm also currently writting some "documentation" for odoc using the new `.mld` support, I'll put that online some time next week.

**Comment by Drup** [comment]
Nice work! So, the way it will work in jbuilder is that I'll just put .mld file inside the same directory than my source file, or in a different place (`/doc`, for example) ?

**Comment by trefis** [comment]
With the [currently proposed implementation](https://github.com/janestreet/jbuilder/pull/290) the `.mld` should live in the same directory as the library sources.

Of course that can be easily changed and is up for discussion with the jbuilder devs.
Also I guess some discussion needs to happen regarding where jbuilder should install the `.mld` file (which it should, if we want odig to work well).

**Comment by dbuenzli** [comment]
> Also I guess some discussion needs to happen regarding where jbuilder should install the .mld file (which it should, if we want odig to work well).

For the fragment for configuring the package page/module index (https://github.com/dbuenzli/odig/issues/18) I think this will be something like `$DOCDIR/$PKG/odig-assets` (there's already an `$DOCDIR/$PKG/odoc-assets` that is looked up until https://github.com/ocaml-doc/odoc/issues/59 gets resolved).

For the manuals I'm open for discussion but it seems to me that it would be more natural to put them somewhere in `$DOCDIR` aswell (maybe `odoc-manual` ?). In general I would rather see these `.mld` manuals live in `doc` directories in source trees rather than along with the `.ml{i}` files in the sources directories. What do people think ?

**Comment by Drup** [comment]
> For the manuals I'm open for discussion but it seems to me that it would be more natural to put them somewhere in $DOCDIR aswell (maybe odoc-manual ?). In general I would rather see these .mld manuals live in doc directories in source trees rather than along with the .ml{i} files in the sources directories. What do people think ?

I agree with all of that.
