### ISSUE TITLE
Html document structure

### ISSUE THREAD

**Issue by xvw** [ocaml-doc/odoc#80]
Hi, first, thanks a lot for your work.
I am creating my own style sheet (for documentation of my possible packages) And I find it quite complicated to make a CSS easy to edit. Yet I think that a simple way to make documents more easily customizable would be to structure the document more "strongly".

For example : 

```html
<header>
  <nav>
     <!-- here, the little caml emoji and the Up button --> 
  </nav>
</header>
<div id="...">
  <h1>OCaml package documentation</h1>
  <p>...</p>
</div>
...
```

The main goal of a more "strongly" structure is to avoid, in the CSS, an abuse of things like that : `nav::nth-child(1) { ... }`.

**Comment by dbuenzli** [comment]
My own experience in writing stylesheets is that having too much structure (`div`itis) precisely leads to have more complex stylesheets.

**Comment by lpw25** [comment]
I suspect that trying to discuss this at a broad level just leads to a religious dispute. I would rather we considered individual changes to the HTML structure on their own merit. So if possible could you describe a particular set of changes that would make your specific stylesheet easier to implement. That should make it easier to discuss the pros and cons of those specific changes.

**Comment by xvw** [comment]
> My own experience in writing stylesheets is that having too much structure (divitis) precisely leads > to have more complex stylesheets.

You are totally right, do not overdo *compartmentalisation*.

IMHO, The only really important point (and useful) would be:

**the first `<nav>` should be in a `<header>`  or have a specific class / id**:
In this way, it is easy to distinguish it from other <nav> (and whose treatment could be more generic).

**

**Comment by dbuenzli** [comment]
> the first <nav> should be in a <header> or have a specific class / id:
> In this way, it is easy to distinguish it from other

There's no other `nav` on the page.

**Comment by xvw** [comment]
Hum... the letters, the tags ?

**Comment by trefis** [comment]
Oh, I think you're talking about the package index page generated by [odig](http://github.com/dbuenzli/odig), not the pages generated by odoc!

**Comment by dbuenzli** [comment]
Indeed, these are easy to address with e.g. `.by-{name,tag} nav` selectors. 

The toplevel `nav` could be distinguished via an `id` (e.g. `top`, `hierarchy`, `tree`) wrapping in a `header` should not be done since those are being used for module names on module pages.

@trefis you'll have to do this on module pages (around [here](56fdc9c2dc03a2281c77e001324bd0affcf54afc)) and I'll have to do it in `odig` for the main `index` page.

**Comment by xvw** [comment]
> Oh, I think you're talking about the package index page generated by odig, not the pages
> generated by odoc!

My bad... sorry ._. 

> The toplevel nav could be distinguished via an id (e.g. top, hierarchy, tree) wrapping in a header 
> should not be done since those are being used for module names on module pages.

You're right. (It was my second proposition)

Thanks a lot.

**Comment by trefis** [comment]
So, `id="top"` on `nav`?

**Comment by dbuenzli** [comment]
Yes.
