### ISSUE TITLE
Replace the `odoc-doc` class by `odoc` 

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/odoc#9]
I'm getting headache at reading the css selectors. Also I wonder if the plan is still to assume that `odoc` is in its own `div` rather than on the whole page otherwise we could simply remove this (better to have simple structures for layout).

**Comment by trefis** [comment]
I went ahead and removed this. The CSS will need updating.

**Comment by dbuenzli** [comment]
This was done a long time ago. Some CSS was upstreamed. Further will be.
